# use_frameworks!

platform :ios, '8.0'

target 'LWColorPicker_Example' do
  pod 'LWColorPicker', :path => '../'

  pod 'Masonry','1.1.0'

  # target 'LWColorPicker_Tests' do
  #   inherit! :search_paths
  #
  # end


end
