use_frameworks!

platform :ios, '8.0'

target 'libColorPicker_Example' do
  pod 'libColorPicker', :path => '../'

  pod 'Masonry','1.1.0'

  # target 'libColorPicker_Tests' do
  #   inherit! :search_paths
  #
  # end


end
